### ISSUE TITLE
new utility chains 🐙

### ISSUE THREAD

**Issue by schemar** [mosaicdao/mosaic-chains#12]
- Port project to TypeScript
  - Mosaic start
  - Mosaic stop
  - Mosaic attach
  - Mosaic list
  - Mosaic logs
  - Documentation
  - Tests
- Create a new chain based on a genesis
- Set up clique validator(s)
- Run an enode and add it to the repository
- Deploy base contracts (state root providers and auxiliary base coin gateways)

![File.jpg](https://images.zenhubusercontent.com/5baa2e199e33b023868f33d9/a1194823-75e8-42c3-a4a2-78b2addc5c41)

**Comment by schemar** [comment]
@benjaminbollen can I please get access to Bala's scripts?

**Comment by schemar** [comment]
https://github.com/ostdotcom/saas-api

**Comment by schemar** [comment]
#14 includes all changes for the port to TypeScript.

**Comment by schemar** [comment]
@benjaminbollen please check this epic and all its children in ZenHub. Do the requirements make sense?

**Comment by deepesh-kn** [comment]
Closing this epic as all the tickets in this epic are closed.
