### ISSUE TITLE
Define generic mosaic config 

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/mosaic-chains#141]
- Make the keys in mosaic-config generic, so that it can represent any ERC20 token.
- Rename the keys
   - simpleTokenAddress -> valueTokenAddress
   - ostComposerAddress -> stakePool
   - ostGatewayOrganizationAddress -> gatewayOrganizationAddress 
   - ostEIP20GatewayAddress -> eip20GatewayAddress
   - ostCoGatewayOrganizationAddress -> coGatewayOrganizationAddress
   - ostPrimeAddress -> utilityTokenAddress
   - ostEIP20CogatewayAddress -> eip20CogatewayAddress
- Make the following keys optional
  - bootNodes
  - genesis

Update the code in mosaic-chains and facilitator to use these new keys.
- Also add below fields in mosaic config
     - baseToken in origin
     - baseToken in aux

**Comment by abhayks1** [comment]
Started working on this ticket...
