### ISSUE TITLE
Add option to choose client in mosaic start command.

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/mosaic-chains#153]
There is no change in the logic of client selection. 
This option will enable the user to choose the client.

Proposed option:

`./mosaic start ropsten --client geth`

`./mosaic start ropsten --client parity`

This ticket is only about starting the node for the given client. 

- This should work for all origin chains.
- This may not work for existing auxiliary chains that are not compatible with parity. In this case throw error.
- For testing purpose, create a new chain with a genesis that is compatible with geth and parity both. 
- Test if the geth client and parity client sync with each other for the same chain.

**Comment by puneet-khushwani-eth** [comment]
#22 is a similar ticket and could be closed after this is handled

**Comment by puneet-khushwani-eth** [comment]
As per #73 restricting the list of supported origin nodes to ropsten, goerli & ethereum mainnet

**Comment by puneet-khushwani-eth** [comment]
We want to support clear data segregation for cases where one wants to start an origin chain with multiple clients. Thus with this ticket have proposed change in structure for .mosaic directory
from:  `~/.mosaic/ropsten/origin`
to:  `~/.mosaic/ropsten/origin-geth` /  `~/.mosaic/ropsten/origin-parity`
