### ISSUE TITLE
Dev chains: Unable to connect to origin and auxiliary chain using ws port

### ISSUE THREAD

**Issue by gulshanvasnani** [mosaicdao/mosaic-chains#157]
Unable to connect to origin and auxiliary chain dev chains using websocket port.

**Comment by puneet-khushwani-eth** [comment]
Looked into this issue, the error says 

`WARN [09-30|07:12:18.448] origin 'http://puneets-macbook-pro.local' not allowed on WS-RPC interface`

Checking the code looks like we would need to add params like `wsorigins=*` even for dev chains.

**Comment by deepesh-kn** [comment]
1. Change the `origin` directory name `origin-geth`.
2. Add `wsorigins=*` in startup.sh in geth commands.
3. Update the readme.md
4. publish it on the docker hub.

**Comment by abhayks1** [comment]
cc: @sarvesh-ost Readme needs to be updated as part of this ticket.
