### ISSUE TITLE
`mosaic start dev` 1/2

### ISSUE THREAD

**Issue by benjaminbollen** [mosaicdao/mosaic-chains#16]
In order to be able to start a local dev setup of a mosaic chain, we require an origin chain.
Create a new dev origin chain.

- [ ] create new origin node (geth) and 
- [ ] deploy OST

### Uncertainties

* what to run as origin? (PoA. fake miner, ...)
* what accounts do we need on origin?
* in order to use this for integration tests, do we require something from the augur nodes we currently use?

**Comment by schemar** [comment]
@schemar to split this ticket into two separate tickets.
