### ISSUE TITLE
Throw error for unknown mosaic commands

### ISSUE THREAD

**Issue by deepesh-kn** [mosaicdao/mosaic-chains#162]
When mosaic commands are used, for wrong commands it fails silently.
Add a check and throw/log proper error message if the wrong command is used.

Also, add the following validation.
- If the origin chain is not listed in the `chainInfo` file, then check if the genesis and boot nodes are present in the `chain` directory. If not present then throw an error.
- For the aux chains, check if the genesis and boot nodes are present in the `chain` directory. If not present then throw an error.

**Comment by sarvesh-ost** [comment]
Observations: 
1. `./mosaic start` & `./mosaic stop` fails silently. 
2. `./mosaic start wrongChain` and  `./mosaic stop wrongChain` fails unexpectedly 
3. `/mosaic attach` fails silently
4. `./mosaic attach wrongchain` fails 
5. `./mosaic logs`  fails silently.
6. `./mosaic logs wrongchain` fails but need to improve error message.
