### ISSUE TITLE
Dev chains should use geth version 1.9.5 instead of 1.8.3

### ISSUE THREAD

**Issue by 0xsarvesh** [mosaicdao/mosaic-chains#248]

**Comment by puneet-khushwani-eth** [comment]
We would also apply istanbul to both chains

**Comment by puneet-khushwani-eth** [comment]
As dev-chains already run with `--allow-insecure-unlock` flag, shorter approach here seems to re-use the existing data dir from the docker image and publish a fresh one with applied changes. 

We can later write an end to end script which would create both chains, deploy relevant contracts, mint OST Prime, fund to some addresses.

**Comment by puneet-khushwani-eth** [comment]
closed via #249
