### ISSUE TITLE
Revise list of networks for parity

### ISSUE THREAD

**Issue by jasonklein** [mosaicdao/mosaic-chains#73]
`mosaic-chains` will run a parity node for specific networks, listed in https://github.com/OpenST/mosaic-chains/blob/master/src/Node/ChainInfo.ts.

This list should be reduced to the following networks: ropsten and ethereum mainnet.

The readme should be updated to reflect the revised list.

**Comment by benjaminbollen** [comment]
ropsten, ethereum mainnet is what Mosaic currently uses.

**Comment by puneet-khushwani-eth** [comment]
handled via #153
